

# nohup env CUDA_VISIBLE_DEVICES=0 HF_HUB_OFFLINE=1 PYTHONPATH=src   python -m lerobot.scripts.train   --config_path=simplify_work/work/0826/train_mstate_step1.yaml --policy.path=models/forsmolvla/smolvla_base > logs/0826/train_mstate_test_step1.log 2>&1 &


dataset:
  repo_id: lerobot/svla_so101_pickplace
  root: training_dataset/0803_with_red/pickplace/first100

batch_size: 64
steps: 26000
output_dir: outputs/train/0902sachet/mtask_grid_2cm
job_name: add_mtask_grid_5cm_sachet
wandb:
  enable: false

policy:
  device: cuda
  repo_id: lerobot/smolvla_base
  type: smolvla
  push_to_hub: false
  # optimizer_lr: 1e-4

# 自定义内容

# 当空的时候就等于baseline
# 会找数据集里面f"mtask_{self.language_tip_mode}.jsonl"的文件
language_tip_mode: "relative_grid_2cm" 
# 控制是将location加到state里面
add_location_to_state:  ""
freeze_except_7_10: false

# 这个什么时候有空才能开始train呢……