

# 改用这个
# nohup env CUDA_VISIBLE_DEVICES=2 HF_HUB_OFFLINE=1 PYTHONPATH=src   python -m lerobot.scripts.train   --config_path=simplify_work/work/train/train_0727_pickplace_100_language.yaml   --policy.path=models/forsmolvla/smolvla_base   --policy.repo_id=lerobot/smolvla_base   > logs/0727/train_100_depth_lang.log 2>&1 &
# 查看

dataset:
  repo_id: lerobot/svla_so101_pickplace
  root: training_dataset/0803_with_red/pickplace/first100

batch_size: 64
steps: 30000
output_dir: outputs/train/0807/language_mtask_structural
job_name: training_pickplace_with_first100_relative_language_struct
wandb:
  enable: false

policy:
  device: cuda
  repo_id: lerobot/smolvla_base
  type: smolvla
  push_to_hub: false

use_depth_image: false
use_force: false
use_language_tip: true
use_true_depth: true
# 这个和jsonl的文件名一致
# "mtask_{self.language_tip_mode}.jsonl"
# language_tip_mode: strcutural
#
add_location_to_state: "pure"
