# CUDA_VISIBLE_DEVICES=2 HF_HUB_OFFLINE=1 python lerobot/scripts/train.py --config_path=simplify_work/work/fine_tune_picplace.yaml
policy:
  path: models/forsmolvla/smolvla_base

dataset:
  repo_id: lerobot/svla_so101_pickplace
  root: training_dataset/0703work/pickplace

batch_size: 64
steps: 20000
output_dir: outputs/train/pickplace
job_name: my_smolvla_training_pickplace
wandb:
  enable: false

policy:
  device: cuda
  repo_id: lerobot/smolvla_base
  type: smolvla