resume: true
dataset:
  repo_id: lerobot/svla_so101_pickplace
  root: training_dataset/0727pickplace/first100

batch_size: 64
steps: 20000
output_dir: outputs/train/0727/depth_100
job_name: training_pickplace_with_first100
wandb:
  enable: false

policy:
  device: cuda
  repo_id: lerobot/smolvla_base
  type: smolvla

use_depth_image: true
use_force: false
use_language_tip: false
