
# 改用这个
# nohup env CUDA_VISIBLE_DEVICES=1 HF_HUB_OFFLINE=1 PYTHONPATH=src   python -m lerobot.scripts.train   --config_path=simplify_work/work/train/fine_tune_0709_first50_depth.yaml   --policy.path=models/forsmolvla/smolvla_base   --policy.repo_id=lerobot/smolvla_base   > train_50_depth.log 2>&1 &
# policy:
#   path: models/forsmolvla/smolvla_base

dataset:
  repo_id: lerobot/svla_so101_pickplace
  root: /home/qwe/.cache/huggingface/lerobot/0725test/test/

batch_size: 64
steps: 20000
output_dir: outputs/nottrain/0709_first100_depth
job_name: training_pickplace_with_first100_depth
wandb:
  enable: false

policy:
  device: cuda
  repo_id: lerobot/smolvla_base
  type: smolvla

use_depth_image: true
use_force: false
use_language_tip: false