# CUDA_VISIBLE_DEVICES=3 HF_HUB_OFFLINE=1 PYTHONPATH=src python -m lerobot.scripts.train --config_path=simplify_work/work/train/fine_tune_0709_first50.yaml --policy.path=models/forsmolvla/smolvla_base --policy.repo_id=lerobot/smolvla_base
# 用的inputfeature有什么？

# 改用这个
# nohup env CUDA_VISIBLE_DEVICES=3 HF_HUB_OFFLINE=1 PYTHONPATH=src   python -m lerobot.scripts.train   --config_path=simplify_work/work/train/fine_tune_0709_first50.yaml   --policy.path=models/forsmolvla/smolvla_base   --policy.repo_id=lerobot/smolvla_base   > train_50.log 2>&1 &
# policy:
#   path: models/forsmolvla/smolvla_base

dataset:
  repo_id: lerobot/svla_so101_pickplace
  root: training_dataset/0709data_first50

batch_size: 64
steps: 20000
output_dir: outputs/train/0709_first50
job_name: training_pickplace_with_first50
wandb:
  enable: false

policy:
  device: cuda
  repo_id: lerobot/smolvla_base
  type: smolvla

use_depth_image: false
use_force: false
use_language_tip: false