
dataset:
  repo_id: lerobot/svla_so101_pickplace
  root: training_dataset/0722new/first50

batch_size: 64
steps: 20000
output_dir: outputs/train/test
job_name: test_use_language
wandb:
  enable: false

policy:
  device: cuda
  repo_id: lerobot/smolvla_base
  type: smolvla

use_depth_image: true
use_force: false
use_language_tip: true